title: Shaswat's Blog
author: Shaswat Prabhat
email: spd1238@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is my tech blog.
  Please bookmark this page for updates.
show_excerpts: true # set to true to show excerpts on the homepage

remote_theme: thelehhman/texture

texture:
  title: Shaswat Prabhat
  tagline: Developer. Reader. Writer.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: ShaswatPrabhat
    github: ShaswatPrabhat
    linkedIn: in/shaswat-prabhat-das/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
